"""initial

Revision ID: 09e3e37205cc
Revises: 
Create Date: 2026-05-13 19:36:40.406505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09e3e37205cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('day_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('registered', 'day_off', 'missed', name='day_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='day_log_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_day_log_user_date')
    )
    op.create_index(op.f('ix_day_logs_date'), 'day_logs', ['date'], unique=False)
    op.create_index(op.f('ix_day_logs_user_id'), 'day_logs', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('health', 'study', 'wellness', 'food', 'sleep', name='goal_category'), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weight BETWEEN 1 AND 3', name='goal_weight_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('goal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_log_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.CheckConstraint('level IN (0.0, 0.4, 0.7, 1.0)', name='entry_level_values'),
    sa.ForeignKeyConstraint(['day_log_id'], ['day_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_log_id', 'goal_id', name='uq_entry_day_goal')
    )
    op.create_index(op.f('ix_goal_entries_day_log_id'), 'goal_entries', ['day_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_entries_day_log_id'), table_name='goal_entries')
    op.drop_table('goal_entries')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_day_logs_user_id'), table_name='day_logs')
    op.drop_index(op.f('ix_day_logs_date'), table_name='day_logs')
    op.drop_table('day_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
